/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cafe_Management_Systems;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author OGUNDIMU SULAIMON
 */
public class Cafe_Management_System extends javax.swing.JFrame {
    private JFrame frame;
    
    double[] drinks = new double[5];
    double[] drinksb = new double[5];
    double[] foods = new double[12];
    double[] cost = new double[3];
    double[] i = new double[17];
    

    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tablewaterb = new javax.swing.JCheckBox();
        purewaterb = new javax.swing.JCheckBox();
        pepsib = new javax.swing.JCheckBox();
        zobob = new javax.swing.JCheckBox();
        kunnub = new javax.swing.JCheckBox();
        tablewater = new javax.swing.JTextField();
        purewater = new javax.swing.JTextField();
        kunnu = new javax.swing.JTextField();
        zobo = new javax.swing.JTextField();
        pepsi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        semob = new javax.swing.JCheckBox();
        amalab = new javax.swing.JCheckBox();
        fufub = new javax.swing.JCheckBox();
        ebab = new javax.swing.JCheckBox();
        iyanb = new javax.swing.JCheckBox();
        riceb = new javax.swing.JCheckBox();
        wheatb = new javax.swing.JCheckBox();
        semo = new javax.swing.JTextField();
        amala = new javax.swing.JTextField();
        eba = new javax.swing.JTextField();
        fufu = new javax.swing.JTextField();
        iyan = new javax.swing.JTextField();
        rice = new javax.swing.JTextField();
        breadb = new javax.swing.JCheckBox();
        beansb = new javax.swing.JCheckBox();
        beans = new javax.swing.JTextField();
        bread = new javax.swing.JTextField();
        wheat = new javax.swing.JTextField();
        meatb = new javax.swing.JCheckBox();
        meat = new javax.swing.JTextField();
        fishb = new javax.swing.JCheckBox();
        fish = new javax.swing.JTextField();
        ponmob = new javax.swing.JCheckBox();
        ponmo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        egusi = new javax.swing.JCheckBox();
        gbegiri = new javax.swing.JCheckBox();
        ewedu = new javax.swing.JCheckBox();
        efoh = new javax.swing.JCheckBox();
        ewuro = new javax.swing.JCheckBox();
        omiobe = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        costofdrinks = new javax.swing.JTextField();
        costoffood = new javax.swing.JTextField();
        servicecharge = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Onje Ibile");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Iya-Alasiri Management System");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\OGUNDIMU SULAIMON\\Desktop\\ARS\\Cafe_Management\\Capture.PNG")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 3, 20)); // NOI18N
        jLabel9.setText("...juen ki o pon owo la");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        tablewaterb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablewaterb.setText("Table Water");
        tablewaterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablewaterbActionPerformed(evt);
            }
        });

        purewaterb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purewaterb.setText("Pure Water");
        purewaterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purewaterbActionPerformed(evt);
            }
        });

        pepsib.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pepsib.setText("Pepsi");
        pepsib.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pepsibMouseDragged(evt);
            }
        });
        pepsib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pepsibMouseClicked(evt);
            }
        });

        zobob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zobob.setText("Zobo");
        zobob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zobobMouseClicked(evt);
            }
        });
        zobob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobobActionPerformed(evt);
            }
        });

        kunnub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kunnub.setText("Kunnu");
        kunnub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kunnubMouseClicked(evt);
            }
        });

        tablewater.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablewater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tablewater.setText("0");
        tablewater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tablewater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablewaterMouseClicked(evt);
            }
        });
        tablewater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablewaterActionPerformed(evt);
            }
        });

        purewater.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purewater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        purewater.setText("0");
        purewater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        purewater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purewaterMouseClicked(evt);
            }
        });

        kunnu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kunnu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kunnu.setText("0");
        kunnu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kunnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kunnuMouseClicked(evt);
            }
        });

        zobo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zobo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zobo.setText("0");
        zobo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        zobo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zoboMouseClicked(evt);
            }
        });

        pepsi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pepsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pepsi.setText("0");
        pepsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pepsiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purewaterb)
                    .addComponent(zobob)
                    .addComponent(kunnub)
                    .addComponent(pepsib)
                    .addComponent(tablewaterb))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purewater, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(kunnu, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(zobo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(pepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(tablewater))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablewaterb)
                    .addComponent(tablewater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purewater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purewaterb))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zobob))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kunnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kunnub))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsib))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        semob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semob.setText("Semo");
        semob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semobMouseClicked(evt);
            }
        });
        semob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semobActionPerformed(evt);
            }
        });

        amalab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amalab.setText("Amala");
        amalab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amalabMouseClicked(evt);
            }
        });

        fufub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fufub.setText("Fufu");
        fufub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fufubMouseClicked(evt);
            }
        });

        ebab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ebab.setText("Eba");
        ebab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ebabMouseClicked(evt);
            }
        });

        iyanb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iyanb.setText("Iyan");
        iyanb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iyanbMouseClicked(evt);
            }
        });
        iyanb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iyanbActionPerformed(evt);
            }
        });

        riceb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        riceb.setText("Rice");
        riceb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ricebMouseClicked(evt);
            }
        });
        riceb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ricebActionPerformed(evt);
            }
        });

        wheatb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wheatb.setText("Wheat");
        wheatb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wheatbMouseClicked(evt);
            }
        });

        semo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semo.setText("0");
        semo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        semo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semoMouseClicked(evt);
            }
        });

        amala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amala.setText("0");
        amala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        amala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amalaMouseClicked(evt);
            }
        });

        eba.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eba.setText("0");
        eba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ebaMouseClicked(evt);
            }
        });

        fufu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fufu.setText("0");
        fufu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fufu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fufuMouseClicked(evt);
            }
        });

        iyan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iyan.setText("0");
        iyan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        iyan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iyanMouseClicked(evt);
            }
        });

        rice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rice.setText("0");
        rice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riceMouseClicked(evt);
            }
        });

        breadb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        breadb.setText("Bread");
        breadb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breadbMouseClicked(evt);
            }
        });
        breadb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadbActionPerformed(evt);
            }
        });

        beansb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        beansb.setText("Beans");
        beansb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beansbMouseClicked(evt);
            }
        });
        beansb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beansbActionPerformed(evt);
            }
        });

        beans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beans.setText("0");
        beans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        beans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beansMouseClicked(evt);
            }
        });

        bread.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bread.setText("0");
        bread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breadMouseClicked(evt);
            }
        });

        wheat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wheat.setText("0");
        wheat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        wheat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wheatMouseClicked(evt);
            }
        });

        meatb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meatb.setText("Meat");
        meatb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meatbMouseClicked(evt);
            }
        });
        meatb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatbActionPerformed(evt);
            }
        });

        meat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        meat.setText("0");
        meat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        meat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meatMouseClicked(evt);
            }
        });

        fishb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fishb.setText("Fish");
        fishb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fishbMouseClicked(evt);
            }
        });
        fishb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishbActionPerformed(evt);
            }
        });

        fish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fish.setText("0");
        fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fishMouseClicked(evt);
            }
        });

        ponmob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ponmob.setText("Ponmo");
        ponmob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ponmobMouseClicked(evt);
            }
        });
        ponmob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponmobActionPerformed(evt);
            }
        });

        ponmo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ponmo.setText("0");
        ponmo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ponmo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ponmoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semob)
                    .addComponent(amalab)
                    .addComponent(fufub)
                    .addComponent(ebab)
                    .addComponent(iyanb)
                    .addComponent(riceb)
                    .addComponent(wheatb)
                    .addComponent(breadb)
                    .addComponent(beansb)
                    .addComponent(meatb)
                    .addComponent(fishb)
                    .addComponent(ponmob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fufu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amala, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eba, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iyan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(beans, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bread, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fish, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ponmo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semob)
                    .addComponent(semo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amalab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fufu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fufub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ebab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iyanb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riceb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheatb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breadb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beansb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meatb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fishb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponmob))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        egusi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        egusi.setText("Egusi");

        gbegiri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gbegiri.setText("Gbegiri");

        ewedu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ewedu.setText("Ewedu");

        efoh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        efoh.setText("Efoh");

        ewuro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ewuro.setText("Ewuro");

        omiobe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        omiobe.setText("Omi-Obe");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egusi)
                    .addComponent(gbegiri))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(efoh)
                    .addComponent(ewedu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ewuro)
                    .addComponent(omiobe))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(egusi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gbegiri)
                            .addComponent(ewedu)
                            .addComponent(omiobe)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ewuro)
                            .addComponent(efoh))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        receipt.setEditable(false);
        receipt.setBackground(new java.awt.Color(255, 255, 204));
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Cost of Drinks");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Cost of Food");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Service charge");

        costofdrinks.setEditable(false);
        costofdrinks.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        costofdrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costofdrinks.setText("0");
        costofdrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        costofdrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costofdrinksActionPerformed(evt);
            }
        });

        costoffood.setEditable(false);
        costoffood.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        costoffood.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costoffood.setText("0");
        costoffood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        costoffood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoffoodActionPerformed(evt);
            }
        });

        servicecharge.setEditable(false);
        servicecharge.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        servicecharge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        servicecharge.setText("3.50");
        servicecharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(111, 111, 111)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(costofdrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(costoffood))
                    .addComponent(servicecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(costofdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(costoffood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(servicecharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Tax");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Sub Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Total");

        tax.setEditable(false);
        tax.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tax.setText("0");
        tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        subtotal.setEditable(false);
        subtotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subtotal.setText("0");
        subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotal)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(total)
                        .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ricebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ricebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ricebActionPerformed

    private void purewaterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purewaterbActionPerformed
         double cCap = Double.parseDouble(costofdrinks.getText());
        double purewaterC = Double.parseDouble(purewater.getText());
        double ipurewater = 10.0;
        
        if(purewaterb.isSelected()){
            i[1] = ipurewater * purewaterC + cCap;
            String pDrink = String.format("%.2f", i[1]);
            //purewater.setText(pDrink);
            costofdrinks.setText(pDrink);
        }
    }//GEN-LAST:event_purewaterbActionPerformed

    private void zobobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zobobActionPerformed

    private void semobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semobActionPerformed

    private void breadbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breadbActionPerformed

    private void beansbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beansbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beansbActionPerformed

    private void meatbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatbActionPerformed

    private void fishbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishbActionPerformed

    private void ponmobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponmobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponmobActionPerformed

    private void costoffoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoffoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoffoodActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frame = new JFrame("Exit");
       
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to to exit?","Abula management System",JOptionPane.YES_NO_OPTION)
                ==JOptionPane.YES_NO_OPTION)
            { System.exit(0);
            
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tax.setText("0");
        subtotal.setText("0");
        total.setText("0");
        costofdrinks.setText("0");
        costoffood.setText("0");
        servicecharge.setText("0");
        receipt.setText("0");
        
        tablewater.setText("0");
        purewater.setText("0");
        zobo.setText("0");
        kunnu.setText("0");
        pepsi.setText("0");
        
        semo.setText("0");
        amala.setText("0");
        fufu.setText("0");
        eba.setText("0");
        iyan.setText("0");
        rice.setText("0");
        wheat.setText("0");
        bread.setText("0");
        beans.setText("0");
        meat.setText("0");
        fish.setText("0");
        ponmo.setText("0");
        
        egusi.setSelected(false);
        gbegiri.setSelected(false);
        efoh.setSelected(false);
        ewedu.setSelected(false);
        ewuro.setSelected(false);
        omiobe.setSelected(false);
        
        tablewaterb.setSelected(false);
        purewaterb.setSelected(false);
        zobob.setSelected(false);
        kunnub.setSelected(false);
        pepsib.setSelected(false);
        
        semob.setSelected(false);
        amalab.setSelected(false);
        fufub.setSelected(false);
        ebab.setSelected(false);
        iyanb.setSelected(false);
        riceb.setSelected(false);
        wheatb.setSelected(false);
        breadb.setSelected(false);
        beansb.setSelected(false);
        meatb.setSelected(false);
        fishb.setSelected(false);
        ponmob.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        drinks[0] = Double.parseDouble(tablewater.getText());
        drinks[1] = Double.parseDouble(purewater.getText());
        drinks[2] = Double.parseDouble(zobo.getText());
        drinks[3] = Double.parseDouble(kunnu.getText());
        drinks[4] = Double.parseDouble(pepsi.getText());
        
        foods[0] = Double.parseDouble(semo.getText());
        foods[1] = Double.parseDouble(amala.getText());
        foods[2] = Double.parseDouble(fufu.getText());
        foods[3] = Double.parseDouble(eba.getText());
        foods[4] = Double.parseDouble(iyan.getText());
        foods[5] = Double.parseDouble(rice.getText());
        foods[6] = Double.parseDouble(wheat.getText());
        foods[7] = Double.parseDouble(bread.getText());
        foods[8] = Double.parseDouble(beans.getText());
        foods[9] = Double.parseDouble(meat.getText());
        foods[10] = Double.parseDouble(fish.getText());
        foods[11] = Double.parseDouble(ponmo.getText());
        
        cost[0] = Double.parseDouble(tax.getText());
        cost[1] = Double.parseDouble(subtotal.getText());
        cost[2] = Double.parseDouble(total.getText());
        
        //----------------------------------------------------------------------
        Calendar timer = Calendar.getInstance();
       timer.getTime();
       
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       String Time = tTime.format(timer.getTime());
       
       SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
       String Date = Tdate.format(timer.getTime());
      
      int refs = 1325 + (int)(Math.random()* 4238);
             
        receipt.append(" Iya Alasiri Management System (UI Branch)" +
                "\n\tReferenceID:   "+refs+
                "\n=============================================================="+ 
                "\nTable water:   "+ drinks[0]+
                "\tPure water:    "+ drinks[1]+
                "\nZobo:          "+ drinks[2]+
                "\tKunnu:         "+ drinks[3]+
                "\nPepsi:         "+ drinks[4]+
                "\n     =========================================       "+    
                "\nSemo:          "+ foods[0]+
                "\tAmala:         "+ foods[1]+
                "\nFufu:          "+ foods[2]+
                "\tEba:           "+ foods[3]+
                "\nIyan:          "+ foods[4]+
                "\tRice:          "+ foods[5]+
                "\nWheat:         "+ foods[6]+
                "\tBread:         "+ foods[7]+
                "\nBeans:         "+ foods[8]+
                "\tMeat:          "+ foods[9]+
                "\nFish:          "+ foods[10]+
                "\tPonmo:         "+ foods[11]+
                "\n     =========================================       "+ 
                "\nTax:           "+ cost[0]+
                "\nSub Total:     "+ cost[1]+
                "\nTotal:         "+ cost[2]+
                "\n     =========================================       "+ 
                "\nDate: " + Date + " \tTime: " +Time
                );
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablewaterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablewaterbActionPerformed
      
        double cCap = Double.parseDouble(costofdrinks.getText());
        double tablewaterC = Double.parseDouble(tablewater.getText());
        double itablewater = 50.0;
        
        if(tablewaterb.isSelected()){
            i[0] = itablewater * tablewaterC + cCap;
            String pDrink = String.format("%.2f", i[0]);
           // tablewater.setText(pDrink);
            costofdrinks.setText(pDrink);
        }
    }//GEN-LAST:event_tablewaterbActionPerformed

    private void tablewaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablewaterActionPerformed
      
    }//GEN-LAST:event_tablewaterActionPerformed

    private void costofdrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costofdrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costofdrinksActionPerformed

    private void zobobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zobobMouseClicked
        double cZobo = Double.parseDouble(costofdrinks.getText());
        double zoboC = Double.parseDouble(zobo.getText());
        double iZobo = 20.0;
        
        if(zobob.isSelected()){
            i[2] = iZobo * zoboC + cZobo;
            String pDrink = String.format("%.2f", i[2]);
           
            costofdrinks.setText(pDrink);
        }
    }//GEN-LAST:event_zobobMouseClicked

    private void kunnubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kunnubMouseClicked
       double cKunnu = Double.parseDouble(costofdrinks.getText());
        double kunnuC = Double.parseDouble(kunnu.getText());
        double iKunnu = 100.0;
        
        if(kunnub.isSelected()){
            i[3] = iKunnu * kunnuC + cKunnu;
            String pDrink = String.format("%.2f", i[3]);
     
            costofdrinks.setText(pDrink);
        }
               
    }//GEN-LAST:event_kunnubMouseClicked

    private void pepsibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsibMouseClicked
        double cPepsi = Double.parseDouble(costofdrinks.getText());
        double PepsiC = Double.parseDouble(pepsi.getText());
        double iPepsi = 120.0;
        
        if(pepsib.isSelected()){
            i[4] = iPepsi * PepsiC + cPepsi;
            String pDrink = String.format("%.2f", i[4]);
            costofdrinks.setText(pDrink);
        }
    }//GEN-LAST:event_pepsibMouseClicked

    private void pepsibMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsibMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pepsibMouseDragged

    private void semobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semobMouseClicked
        double cSemo = Double.parseDouble(costoffood.getText());
        double semoC = Double.parseDouble(semo.getText());
        double isemo = 30.0;
        
        if(semob.isSelected()){
            i[5] = isemo * semoC + cSemo;
            String pDrink = String.format("%.2f", i[5]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_semobMouseClicked

    private void amalabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amalabMouseClicked
        double cAmala = Double.parseDouble(costoffood.getText());
        double amalaC = Double.parseDouble(amala.getText());
        double iamala = 30.0;
        
        if(amalab.isSelected()){
            i[6] = iamala * amalaC + cAmala;
            String pDrink = String.format("%.2f", i[6]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_amalabMouseClicked

    private void fufubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fufubMouseClicked
         double cFufu = Double.parseDouble(costoffood.getText());
        double fufuC = Double.parseDouble(fufu.getText());
        double ifufu = 50.0;
        
        if(fufub.isSelected()){
            i[7] = ifufu * fufuC + cFufu;
            String pDrink = String.format("%.2f", i[7]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_fufubMouseClicked

    private void ebabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebabMouseClicked
        double cEba = Double.parseDouble(costoffood.getText());
        double ebaC = Double.parseDouble(eba.getText());
        double ieba= 30.0;
        
        if(ebab.isSelected()){
            i[8] = ieba * ebaC + cEba;
            String pDrink = String.format("%.2f", i[8]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_ebabMouseClicked

    private void iyanbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iyanbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iyanbActionPerformed

    private void iyanbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iyanbMouseClicked
           double ciyan = Double.parseDouble(costoffood.getText());
        double iyanC = Double.parseDouble(iyan.getText());
        double iiyan = 50.0;
        
        if(iyanb.isSelected()){
            i[9] = iiyan * iyanC + ciyan;
            String pDrink = String.format("%.2f", i[9]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_iyanbMouseClicked

    private void ricebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ricebMouseClicked
          double crice = Double.parseDouble(costoffood.getText());
        double riceC = Double.parseDouble(rice.getText());
        double irice = 50.0;
        
        if(riceb.isSelected()){
            i[10] = irice * riceC + crice;
            String pDrink = String.format("%.2f", i[10]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_ricebMouseClicked

    private void wheatbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatbMouseClicked
        double cwheat = Double.parseDouble(costoffood.getText());
        double wheatC = Double.parseDouble(wheat.getText());
        double iwheat = 50.0;
        
        if(wheatb.isSelected()){
            i[11] = iwheat * wheatC + cwheat;
            String pDrink = String.format("%.2f", i[11]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_wheatbMouseClicked

    private void breadbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breadbMouseClicked
        double cbread = Double.parseDouble(costoffood.getText());
        double breadC = Double.parseDouble(bread.getText());
        double ibread = 50.0;
        
        if(breadb.isSelected()){
            i[12] = ibread * breadC + cbread;
            String pDrink = String.format("%.2f", i[12]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_breadbMouseClicked

    private void beansbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansbMouseClicked
        double cbeans = Double.parseDouble(costoffood.getText());
        double beansC = Double.parseDouble(beans.getText());
        double ibeans = 50.0;
        
        if(beansb.isSelected()){
            i[13] = ibeans * beansC + cbeans;
            String pDrink = String.format("%.2f", i[13]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_beansbMouseClicked

    private void meatbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatbMouseClicked
         double cmeat = Double.parseDouble(costoffood.getText());
        double meatC = Double.parseDouble(meat.getText());
        double imeat = 50.0;
        
        if(meatb.isSelected()){
            i[14] = imeat * meatC + cmeat;
            String pDrink = String.format("%.2f", i[14]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_meatbMouseClicked

    private void fishbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishbMouseClicked
       double cfish = Double.parseDouble(costoffood.getText());
        double fishC = Double.parseDouble(fish.getText());
        double ifish = 50.0;
        
        if(fishb.isSelected()){
            i[15] = ifish * fishC + cfish;
            String pDrink = String.format("%.2f", i[15]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_fishbMouseClicked

    private void ponmobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ponmobMouseClicked
        double cponmo = Double.parseDouble(costoffood.getText());
        double ponmoC = Double.parseDouble(ponmo.getText());
        double iponmo = 20.0;
        
        if(ponmob.isSelected()){
            i[16] = iponmo * ponmoC + cponmo;
            String pDrink = String.format("%.2f", i[16]);
            costoffood.setText(pDrink);
        }
    }//GEN-LAST:event_ponmobMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        drinks[0] = Double.parseDouble(costofdrinks.getText());
        drinks[1] = Double.parseDouble(costoffood.getText());
        drinks[2] = Double.parseDouble(servicecharge.getText());
        
        double cTotal = drinks[0] + drinks[1] + drinks[2];
        
        String iTaxTotal = String.format("%.2f", cTotal/100);
        tax.setText(iTaxTotal);
        
        String subTotal = String.format("%.2f", cTotal);
        subtotal.setText(subTotal);
        
        String Total = String.format("%.2f", (cTotal+(cTotal/100)));
        total.setText(Total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void purewaterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purewaterMouseClicked
        purewater.setText(null);
    }//GEN-LAST:event_purewaterMouseClicked

    private void zoboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoboMouseClicked
        zobo.setText(null);
    }//GEN-LAST:event_zoboMouseClicked

    private void kunnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kunnuMouseClicked
        kunnu.setText(null);
    }//GEN-LAST:event_kunnuMouseClicked

    private void pepsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsiMouseClicked
        pepsi.setText(null);
    }//GEN-LAST:event_pepsiMouseClicked

    private void tablewaterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablewaterMouseClicked
        tablewater.setText(null);
    }//GEN-LAST:event_tablewaterMouseClicked

    private void semoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semoMouseClicked
        semo.setText(null);
    }//GEN-LAST:event_semoMouseClicked

    private void amalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amalaMouseClicked
        amala.setText(null);
    }//GEN-LAST:event_amalaMouseClicked

    private void fufuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fufuMouseClicked
        // TODO add your handling code here:
        fufu.setText(null);
    }//GEN-LAST:event_fufuMouseClicked

    private void ebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebaMouseClicked
        // TODO add your handling code here:
        eba.setText(null);
    }//GEN-LAST:event_ebaMouseClicked

    private void iyanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iyanMouseClicked
        // TODO add your handling code here:
        iyan.setText(null);
    }//GEN-LAST:event_iyanMouseClicked

    private void riceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riceMouseClicked
        // TODO add your handling code here:
        rice.setText(null);
    }//GEN-LAST:event_riceMouseClicked

    private void wheatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatMouseClicked
        // TODO add your handling code here:
        wheat.setText(null);
    }//GEN-LAST:event_wheatMouseClicked

    private void breadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breadMouseClicked
        // TODO add your handling code here:
        bread.setText(null);
    }//GEN-LAST:event_breadMouseClicked

    private void beansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseClicked
        // TODO add your handling code here:
        beans.setText(null);
    }//GEN-LAST:event_beansMouseClicked

    private void meatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatMouseClicked
        // TODO add your handling code here:
        meat.setText(null);
    }//GEN-LAST:event_meatMouseClicked

    private void fishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishMouseClicked
        // TODO add your handling code here:
        fish.setText(null);
    }//GEN-LAST:event_fishMouseClicked

    private void ponmoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ponmoMouseClicked
        // TODO add your handling code here:
        ponmo.setText(null);
    }//GEN-LAST:event_ponmoMouseClicked

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amala;
    private javax.swing.JCheckBox amalab;
    private javax.swing.JTextField beans;
    private javax.swing.JCheckBox beansb;
    private javax.swing.JTextField bread;
    private javax.swing.JCheckBox breadb;
    private javax.swing.JTextField costofdrinks;
    private javax.swing.JTextField costoffood;
    private javax.swing.JTextField eba;
    private javax.swing.JCheckBox ebab;
    private javax.swing.JCheckBox efoh;
    private javax.swing.JCheckBox egusi;
    private javax.swing.JCheckBox ewedu;
    private javax.swing.JCheckBox ewuro;
    private javax.swing.JTextField fish;
    private javax.swing.JCheckBox fishb;
    private javax.swing.JTextField fufu;
    private javax.swing.JCheckBox fufub;
    private javax.swing.JCheckBox gbegiri;
    private javax.swing.JTextField iyan;
    private javax.swing.JCheckBox iyanb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kunnu;
    private javax.swing.JCheckBox kunnub;
    private javax.swing.JTextField meat;
    private javax.swing.JCheckBox meatb;
    private javax.swing.JCheckBox omiobe;
    private javax.swing.JTextField pepsi;
    private javax.swing.JCheckBox pepsib;
    private javax.swing.JTextField ponmo;
    private javax.swing.JCheckBox ponmob;
    private javax.swing.JTextField purewater;
    private javax.swing.JCheckBox purewaterb;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTextField rice;
    private javax.swing.JCheckBox riceb;
    private javax.swing.JTextField semo;
    private javax.swing.JCheckBox semob;
    private javax.swing.JTextField servicecharge;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tablewater;
    private javax.swing.JCheckBox tablewaterb;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JTextField wheat;
    private javax.swing.JCheckBox wheatb;
    private javax.swing.JTextField zobo;
    private javax.swing.JCheckBox zobob;
    // End of variables declaration//GEN-END:variables
}
